# Generated by Django 3.2.13 on 2022-07-12 20:32

from django.db import migrations, models
import djrichtextfield.models
import taggit.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taggit', '0005_auto_20220424_2025'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', djrichtextfield.models.RichTextField()),
                ('slug', models.SlugField(unique=True)),
                ('image', models.CharField(default='/default_recipe_image.png', max_length=255)),
                ('tags', taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
            ],
        ),
    ]
