# Generated by Django 3.2.13 on 2022-06-20 07:11

from django.db import migrations
import djrichtextfield.models


class Migration(migrations.Migration):

    dependencies = [
        ('cukbuk_app', '0004_alter_recipe_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='description',
            field=djrichtextfield.models.RichTextField(),
        ),
    ]
