# Generated by Django 3.2.13 on 2022-07-01 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cukbuk_app', '0006_remove_recipe_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='tags',
            field=models.ManyToManyField(to='cukbuk_app.Tag'),
        ),
    ]
